### ISSUE TITLE
"Elements of SQL" Query Runner Broken?

### ISSUE THREAD

**Issue by bmac423** [udacity/fsnd-issues#103]

**Comment by bmac423** [comment]
I'm going through the "Elements of SQL" section of the backend section, and I've been unable to run any queries. I'm fairly familiar with SQL, and I don't think it has to do with my query structure or syntax. I'm planning on cruising through, and just reading the materials, but I though I'd bring it to your attention. Loving the coursework so far, btw! Thanks!

Here's the stacktrace I'm seeing on lesson 8.
~~~
Traceback (most recent call last):
  File "vm_main.py", line 33, in <module>
    import main
  File "/tmp/vmuser_ljloonwhuh/main.py", line 2, in <module>
    import studentMain
  File "/tmp/vmuser_ljloonwhuh/studentMain.py", line 4, in <module>
    import driver
  File "/tmp/vmuser_ljloonwhuh/driver.py", line 20
SyntaxError: Non-ASCII character '\xc3' in file /tmp/vmuser_ljloonwhuh/driver.py on line 20, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
~~~

![sql_trace.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a3d290b81677c00119d83a3/125516c66e82c728ace21e0d46fb85961c9691a88cecfd0fe64de29b234324676b5ee17e29d0b12cee432b525c5d4cfe43585f46f9fadd79a2e36f62964e49bc8f3900299f7744eeaa880dbd03b0218e4e86bfb98d45c1e0352de099c2.png)

Yesterday, on section 2, I got this:

~~~
Traceback (most recent call last):
  File "vm_main.py", line 33, in <module>
    import main
  File "/tmp/vmuser_qdtvsjfjho/main.py", line 2, in <module>
    import studentMain
  File "/tmp/vmuser_qdtvsjfjho/studentMain.py", line 4, in <module>
    import driver
  File "/tmp/vmuser_qdtvsjfjho/driver.py", line 22
    se não forem linhas:
       ^
SyntaxError: invalid syntax
~~~

**Comment by karlud** [comment]
Thanks for reporting this! There was a translation-related bug in our system that broke these quizzes. They should be fixed now. Sorry for the trouble!
