### ISSUE TITLE
SQL Quizzes Not Working

### ISSUE THREAD

**Issue by JessicaBettencourt** [udacity/fsnd-issues#106]
https://classroom.udacity.com/nanodegrees/nd004/parts/8d3e23e1-9ab6-47eb-b4f3-d5dc7ef27bf0/modules/bc51d967-cb21-46f4-90ea-caf73439dc59/lessons/b8756d6f-2072-4511-9a46-33579413153d/concepts/92db779d-1888-47bd-9f6b-3e3d22161a07

Hi - in the quiz on this page [1], when testing (Test Run) it is now returning an error: 
Traceback (most recent call last): File "vm_main.py", line 33, in <module> import main File "/tmp/vmuser_rbkkbohxvl/main.py", line 2, in <module> import studentMain File "/tmp/vmuser_rbkkbohxvl/studentMain.py", line 1, in <module> import sqlite3, ascii File "/tmp/vmuser_rbkkbohxvl/ascii.py", line 21 para r em linhas ^ SyntaxError: invalid syntax

(reported by several students and mentors)

**Comment by karlud** [comment]
These were broken by a bad translation process. (Students might notice a bit of Portuguese text in that error message, where there should be Python code.)

I'm fixing them but it will take a little time.

**Comment by JessicaBettencourt** [comment]
Thanks for the update!
